"""init

Revision ID: dbe2d23588c5
Revises: 
Create Date: 2021-05-10 16:14:48.751415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe2d23588c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('outlink', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('aurl', sa.String(length=512), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('isadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('texts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('pubtime', sa.String(length=16), nullable=True),
    sa.Column('stime', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(length=16), nullable=True),
    sa.Column('ak', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('ctext', sa.Text(), nullable=True),
    sa.Column('ptext', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('desp', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    op.drop_table('dogs')
    # ### end Alembic commands ###
